name: Lint

on:
  push:
  pull_request:
    types: [opened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"
          cache: "pip"
      - run: pip install black==23.3
      - run: black --check --diff ./dynaconf_aws_loader
